name: Running Code Coverage

on: 
  pull_request:
  push:
    branches:
      - devel
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run the tests
        env: 
          CONFIG_FILE_BASE64: ${{ secrets.CONFIG_FILE_BASE64 }}
        run: |
          echo "$CONFIG_FILE_BASE64" > config.js.base64
          base64 --decode config.js.base64 > config.js
          npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
